services:
  - type: web
    name: securecam-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: SPREADSHEET_ID
        value: your_google_sheet_id